# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:qVeD15NftQ5L7Cpzalwmj9BVN1Zgp1MQAkMaejYq3+9SKKAXyntYuA==,iv:TTDm3CsT6Heq+npbo08/1NqV6W5rQw4XiZDRD43a84A=,tag:OBo2VogEOKauKrQzoJvO3w==,type:str]
sops:
  age:
    - recipient: age1azprfdz0s4pxzf4pqrhqkuk07vupl8wgcsrvdefprfk97lrrue5svyudmf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VlFmUDkxMVE0MW1tSnNV
        TGsvd3dmc0R0alorclFFUWNDSncxMFJub3lnCnFKdnM0STA5dG43bkd2OFR4WFQz
        djNCMHNJeFV6QWpHUVptTDJPNnE1aGsKLS0tIGRGdGV5amU4Mi9rdU9TVkg0QTBX
        TWJXTzRjNHhjTUFLanUrN1BzeUw0dkUKktGiAQca1zbgfZd46aOusNTGttuawhC3
        aip/1q1PeW1P2Xria5XFQQcZfkd5RxZ0MrpsxYipongTtbbUNmyAag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-28T18:26:05Z"
  mac: ENC[AES256_GCM,data:8udZWTOYh0tQwCwBEgTBCvZljavOEa+yPAkIoPo2skc56Vnewtsc/eUexD4e8egVt96rSr/o8ZiA1a2QFTG9lLI8GXFRtsJ4OVxvWm8Mo8SzvgRu/t2R08gecpVKFsTsXmdCnxFKJG1Uj6y7//zC9khHlKHetfQyfsdfYyWwrAM=,iv:P4E/Yv5kIzNeB4lYpAXKODI8WiORHvC3WYYMbP/kF0U=,tag:HuscI2grrH3zB1YG00Mx4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
